//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Web Services Description Language Utility
//Mono Framework v2.0.50727.5485
//
namespace Svc_WebService {
    using System.Xml.Serialization;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Diagnostics;
    using System.Configuration;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CommonReceiveServiceSoap", Namespace="http://www.ctrip.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResponseBase))]
    public partial class CommonReceiveService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private CtripSoapHeader ctripSoapHeaderValueField;
        
        private System.Threading.SendOrPostCallback GetTokenOperationCompleted;
        
        private System.Threading.SendOrPostCallback RequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback AdapterRequestOperationCompleted;
        
        /// <remarks/>
        public CommonReceiveService()
        {
            this.Url = "http://receive.vendor.hotel.ctrip.com/receive-common1/CommonReceiveService.asmx";//生产地址
            //this.Url = "http://vendor-hotel.fat.ctripqa.com/receive-common1/CommonReceiveService.asmx";//测试地址
        }
        
        public CtripSoapHeader CtripSoapHeaderValue {
            get {
                return this.ctripSoapHeaderValueField;
            }
            set {
                this.ctripSoapHeaderValueField = value;
            }
        }
        
        /// <remarks/>
        public event GetTokenCompletedEventHandler GetTokenCompleted;
        
        /// <remarks/>
        public event RequestCompletedEventHandler RequestCompleted;
        
        /// <remarks/>
        public event AdapterRequestCompletedEventHandler AdapterRequestCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CtripSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ctrip.com/GetToken", RequestNamespace="http://www.ctrip.com/", ResponseNamespace="http://www.ctrip.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CtripSoapResponse GetToken() {
            object[] results = this.Invoke("GetToken", new object[0]);
            return ((CtripSoapResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetTokenAsync() {
            this.GetTokenAsync(null);
        }
        
        /// <remarks/>
        public void GetTokenAsync(object userState) {
            if ((this.GetTokenOperationCompleted == null)) {
                this.GetTokenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTokenOperationCompleted);
            }
            this.InvokeAsync("GetToken", new object[0], this.GetTokenOperationCompleted, userState);
        }
        
        private void OnGetTokenOperationCompleted(object arg) {
            if ((this.GetTokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTokenCompleted(this, new GetTokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CtripSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ctrip.com/Request", RequestNamespace="http://www.ctrip.com/", ResponseNamespace="http://www.ctrip.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CtripSoapResponse Request(string requestXml) {
            object[] results = this.Invoke("Request", new object[] {
                        requestXml});
            return ((CtripSoapResponse)(results[0]));
        }
        
        /// <remarks/>
        public void RequestAsync(string requestXml) {
            this.RequestAsync(requestXml, null);
        }
        
        /// <remarks/>
        public void RequestAsync(string requestXml, object userState) {
            if ((this.RequestOperationCompleted == null)) {
                this.RequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestOperationCompleted);
            }
            this.InvokeAsync("Request", new object[] {
                        requestXml}, this.RequestOperationCompleted, userState);
        }
        
        private void OnRequestOperationCompleted(object arg) {
            if ((this.RequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequestCompleted(this, new RequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ctrip.com/AdapterRequest", RequestNamespace="http://www.ctrip.com/", ResponseNamespace="http://www.ctrip.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AdapterRequest(string requestXml) {
            object[] results = this.Invoke("AdapterRequest", new object[] {
                        requestXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AdapterRequestAsync(string requestXml) {
            this.AdapterRequestAsync(requestXml, null);
        }
        
        /// <remarks/>
        public void AdapterRequestAsync(string requestXml, object userState) {
            if ((this.AdapterRequestOperationCompleted == null)) {
                this.AdapterRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdapterRequestOperationCompleted);
            }
            this.InvokeAsync("AdapterRequest", new object[] {
                        requestXml}, this.AdapterRequestOperationCompleted, userState);
        }
        
        private void OnAdapterRequestOperationCompleted(object arg) {
            if ((this.AdapterRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AdapterRequestCompleted(this, new AdapterRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ctrip.com/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ctrip.com/", IsNullable=false)]
    public partial class CtripSoapHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string loginField;
        
        private string passwordField;
        
        private string companyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ctrip.com/")]
    public partial class OptionalCategory {
        
        private int optionalCategoryIDField;
        
        private string categoryNameCNField;
        
        private string categoryNameENField;
        
        /// <remarks/>
        public int OptionalCategoryID {
            get {
                return this.optionalCategoryIDField;
            }
            set {
                this.optionalCategoryIDField = value;
            }
        }
        
        /// <remarks/>
        public string CategoryNameCN {
            get {
                return this.categoryNameCNField;
            }
            set {
                this.categoryNameCNField = value;
            }
        }
        
        /// <remarks/>
        public string CategoryNameEN {
            get {
                return this.categoryNameENField;
            }
            set {
                this.categoryNameENField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ctrip.com/")]
    public partial class GetOptionalCategoryResponse {
        
        private OptionalCategory[] optionalCategoryListField;
        
        private string responseStatusField;
        
        /// <remarks/>
        public OptionalCategory[] OptionalCategoryList {
            get {
                return this.optionalCategoryListField;
            }
            set {
                this.optionalCategoryListField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ctrip.com/")]
    public partial class SetOptionalHotelResponse {
        
        private string responseStatusField;
        
        private int optionalHotelIDField;
        
        /// <remarks/>
        public string ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
        
        /// <remarks/>
        public int OptionalHotelID {
            get {
                return this.optionalHotelIDField;
            }
            set {
                this.optionalHotelIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ctrip.com/")]
    public partial class HotelRoomEntity {
        
        private int masterRoomField;
        
        private int roomField;
        
        private string roomNameField;
        
        private int breakfastField;
        
        private string twinBedField;
        
        private string kingSizeField;
        
        private int personField;
        
        private string allowAddBedField;
        
        private string balanceTypeField;
        
        private string ratePlanCodeField;
        
        /// <remarks/>
        public int MasterRoom {
            get {
                return this.masterRoomField;
            }
            set {
                this.masterRoomField = value;
            }
        }
        
        /// <remarks/>
        public int Room {
            get {
                return this.roomField;
            }
            set {
                this.roomField = value;
            }
        }
        
        /// <remarks/>
        public string RoomName {
            get {
                return this.roomNameField;
            }
            set {
                this.roomNameField = value;
            }
        }
        
        /// <remarks/>
        public int Breakfast {
            get {
                return this.breakfastField;
            }
            set {
                this.breakfastField = value;
            }
        }
        
        /// <remarks/>
        public string TwinBed {
            get {
                return this.twinBedField;
            }
            set {
                this.twinBedField = value;
            }
        }
        
        /// <remarks/>
        public string KingSize {
            get {
                return this.kingSizeField;
            }
            set {
                this.kingSizeField = value;
            }
        }
        
        /// <remarks/>
        public int Person {
            get {
                return this.personField;
            }
            set {
                this.personField = value;
            }
        }
        
        /// <remarks/>
        public string AllowAddBed {
            get {
                return this.allowAddBedField;
            }
            set {
                this.allowAddBedField = value;
            }
        }
        
        /// <remarks/>
        public string BalanceType {
            get {
                return this.balanceTypeField;
            }
            set {
                this.balanceTypeField = value;
            }
        }
        
        /// <remarks/>
        public string RatePlanCode {
            get {
                return this.ratePlanCodeField;
            }
            set {
                this.ratePlanCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ctrip.com/")]
    public partial class ChildHotelEntity {
        
        private int hotelField;
        
        private HotelRoomEntity[] roomResponseItemField;
        
        /// <remarks/>
        public int Hotel {
            get {
                return this.hotelField;
            }
            set {
                this.hotelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RoomResponseItem")]
        public HotelRoomEntity[] RoomResponseItem {
            get {
                return this.roomResponseItemField;
            }
            set {
                this.roomResponseItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ctrip.com/")]
    public partial class MasterRoomEntity {
        
        private int masterRoomField;
        
        private string roomNameField;
        
        /// <remarks/>
        public int MasterRoom {
            get {
                return this.masterRoomField;
            }
            set {
                this.masterRoomField = value;
            }
        }
        
        /// <remarks/>
        public string RoomName {
            get {
                return this.roomNameField;
            }
            set {
                this.roomNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ctrip.com/")]
    public partial class MasterHotelEntity {
        
        private int hotelField;
        
        private string hotelNameField;
        
        private string cityField;
        
        private string cityNameField;
        
        private MasterRoomEntity[] roomResponseItemField;
        
        private ChildHotelEntity childHotelField;
        
        /// <remarks/>
        public int Hotel {
            get {
                return this.hotelField;
            }
            set {
                this.hotelField = value;
            }
        }
        
        /// <remarks/>
        public string HotelName {
            get {
                return this.hotelNameField;
            }
            set {
                this.hotelNameField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string CityName {
            get {
                return this.cityNameField;
            }
            set {
                this.cityNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RoomResponseItem")]
        public MasterRoomEntity[] RoomResponseItem {
            get {
                return this.roomResponseItemField;
            }
            set {
                this.roomResponseItemField = value;
            }
        }
        
        /// <remarks/>
        public ChildHotelEntity ChildHotel {
            get {
                return this.childHotelField;
            }
            set {
                this.childHotelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ctrip.com/")]
    public partial class HotelResponseEntity {
        
        private MasterHotelEntity masterHotelField;
        
        /// <remarks/>
        public MasterHotelEntity MasterHotel {
            get {
                return this.masterHotelField;
            }
            set {
                this.masterHotelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ctrip.com/")]
    public partial class GetMappingInfoListReponse {
        
        private System.Nullable<int> supplierIDField;
        
        private string supplierNameField;
        
        private HotelResponseEntity[] hotelResponseItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SupplierID {
            get {
                return this.supplierIDField;
            }
            set {
                this.supplierIDField = value;
            }
        }
        
        /// <remarks/>
        public string SupplierName {
            get {
                return this.supplierNameField;
            }
            set {
                this.supplierNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("HotelResponseItem")]
        public HotelResponseEntity[] HotelResponseItem {
            get {
                return this.hotelResponseItemField;
            }
            set {
                this.hotelResponseItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ctrip.com/")]
    public partial class GetMasterHotelInfoResponse {
        
        private string resultField;
        
        /// <remarks/>
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ctrip.com/")]
    public partial class OptionalStandard {
        
        private int optionalStandardIDField;
        
        private int optionalCategoryIDField;
        
        private string optionalNameField;
        
        private int unitTypeField;
        
        /// <remarks/>
        public int OptionalStandardID {
            get {
                return this.optionalStandardIDField;
            }
            set {
                this.optionalStandardIDField = value;
            }
        }
        
        /// <remarks/>
        public int OptionalCategoryID {
            get {
                return this.optionalCategoryIDField;
            }
            set {
                this.optionalCategoryIDField = value;
            }
        }
        
        /// <remarks/>
        public string OptionalName {
            get {
                return this.optionalNameField;
            }
            set {
                this.optionalNameField = value;
            }
        }
        
        /// <remarks/>
        public int UnitType {
            get {
                return this.unitTypeField;
            }
            set {
                this.unitTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ctrip.com/")]
    public partial class GetOptionalStandardResponse {
        
        private OptionalStandard[] optionalStandardListField;
        
        private string responseStatusField;
        
        /// <remarks/>
        public OptionalStandard[] OptionalStandardList {
            get {
                return this.optionalStandardListField;
            }
            set {
                this.optionalStandardListField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ctrip.com/")]
    public partial class OrderCheckInNoticeResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ctrip.com/")]
    public partial class GetOptionalHotelVacationTicketType {
        
        private long vacationTicketIDField;
        
        private int optionalHotelIDField;
        
        private long resourceIDField;
        
        private System.Nullable<long> productIDField;
        
        private System.DateTime lastSyncTimeField;
        
        private string closeReasonField;
        
        private short syncStatusField;
        
        private string syncResultField;
        
        private System.Nullable<System.DateTime> dataChange_CreateTimeField;
        
        private System.Nullable<System.DateTime> dataChange_LastTimeField;
        
        private System.Nullable<decimal> cashBackAmountField;
        
        /// <remarks/>
        public long VacationTicketID {
            get {
                return this.vacationTicketIDField;
            }
            set {
                this.vacationTicketIDField = value;
            }
        }
        
        /// <remarks/>
        public int OptionalHotelID {
            get {
                return this.optionalHotelIDField;
            }
            set {
                this.optionalHotelIDField = value;
            }
        }
        
        /// <remarks/>
        public long ResourceID {
            get {
                return this.resourceIDField;
            }
            set {
                this.resourceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> ProductID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastSyncTime {
            get {
                return this.lastSyncTimeField;
            }
            set {
                this.lastSyncTimeField = value;
            }
        }
        
        /// <remarks/>
        public string CloseReason {
            get {
                return this.closeReasonField;
            }
            set {
                this.closeReasonField = value;
            }
        }
        
        /// <remarks/>
        public short SyncStatus {
            get {
                return this.syncStatusField;
            }
            set {
                this.syncStatusField = value;
            }
        }
        
        /// <remarks/>
        public string SyncResult {
            get {
                return this.syncResultField;
            }
            set {
                this.syncResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DataChange_CreateTime {
            get {
                return this.dataChange_CreateTimeField;
            }
            set {
                this.dataChange_CreateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DataChange_LastTime {
            get {
                return this.dataChange_LastTimeField;
            }
            set {
                this.dataChange_LastTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> CashBackAmount {
            get {
                return this.cashBackAmountField;
            }
            set {
                this.cashBackAmountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ctrip.com/")]
    public partial class GetOptionalHotelRelationType {
        
        private long optionalHotelRelationIDField;
        
        private int optionalHotelIDField;
        
        private int productIDField;
        
        private int productTypeField;
        
        private string operatorUidField;
        
        private System.Nullable<System.DateTime> dataChange_CreateTimeField;
        
        private System.Nullable<System.DateTime> dataChange_LastTimeField;
        
        /// <remarks/>
        public long OptionalHotelRelationID {
            get {
                return this.optionalHotelRelationIDField;
            }
            set {
                this.optionalHotelRelationIDField = value;
            }
        }
        
        /// <remarks/>
        public int OptionalHotelID {
            get {
                return this.optionalHotelIDField;
            }
            set {
                this.optionalHotelIDField = value;
            }
        }
        
        /// <remarks/>
        public int ProductID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        public int ProductType {
            get {
                return this.productTypeField;
            }
            set {
                this.productTypeField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorUid {
            get {
                return this.operatorUidField;
            }
            set {
                this.operatorUidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DataChange_CreateTime {
            get {
                return this.dataChange_CreateTimeField;
            }
            set {
                this.dataChange_CreateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DataChange_LastTime {
            get {
                return this.dataChange_LastTimeField;
            }
            set {
                this.dataChange_LastTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ctrip.com/")]
    public partial class OptionalHotel {
        
        private int optionalHotelIDField;
        
        private int optionalStandardIDField;
        
        private string captionDispCNField;
        
        private string captionDispENField;
        
        private string unitDispCNField;
        
        private string unitDispENField;
        
        private string descriptionCNField;
        
        private string descriptionENField;
        
        private string currencyCodeField;
        
        private short maxAmountTypeField;
        
        private System.Nullable<int> maxAmountValueField;
        
        private short isRequiredField;
        
        private short isPackageField;
        
        private short differentSupplierField;
        
        private short allowRemarkField;
        
        private string remarkNoticeCNField;
        
        private string remarkNoticeENField;
        
        private System.Nullable<int> timeLimitField;
        
        private string channelIDField;
        
        private System.Nullable<bool> hiddenSalePriceField;
        
        private string isVisibleField;
        
        private short optionalHotelTypeField;
        
        private System.Nullable<short> exchangeTypeField;
        
        private string tripCautionField;
        
        private string importantClauseField;
        
        private System.Nullable<short> optionalExtTypeField;
        
        private GetOptionalHotelRelationType getOptionalHotelRelationTypeField;
        
        private GetOptionalHotelVacationTicketType getOptionalHotelVacationTicketTypeField;
        
        private string isDeleteField;
        
        private string internalMemoField;
        
        private string operationNotesField;
        
        private string bookLimitField;
        
        private string groupNameField;
        
        private string packageDescField;
        
        /// <remarks/>
        public int OptionalHotelID {
            get {
                return this.optionalHotelIDField;
            }
            set {
                this.optionalHotelIDField = value;
            }
        }
        
        /// <remarks/>
        public int OptionalStandardID {
            get {
                return this.optionalStandardIDField;
            }
            set {
                this.optionalStandardIDField = value;
            }
        }
        
        /// <remarks/>
        public string CaptionDispCN {
            get {
                return this.captionDispCNField;
            }
            set {
                this.captionDispCNField = value;
            }
        }
        
        /// <remarks/>
        public string CaptionDispEN {
            get {
                return this.captionDispENField;
            }
            set {
                this.captionDispENField = value;
            }
        }
        
        /// <remarks/>
        public string UnitDispCN {
            get {
                return this.unitDispCNField;
            }
            set {
                this.unitDispCNField = value;
            }
        }
        
        /// <remarks/>
        public string UnitDispEN {
            get {
                return this.unitDispENField;
            }
            set {
                this.unitDispENField = value;
            }
        }
        
        /// <remarks/>
        public string DescriptionCN {
            get {
                return this.descriptionCNField;
            }
            set {
                this.descriptionCNField = value;
            }
        }
        
        /// <remarks/>
        public string DescriptionEN {
            get {
                return this.descriptionENField;
            }
            set {
                this.descriptionENField = value;
            }
        }
        
        /// <remarks/>
        public string CurrencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
            }
        }
        
        /// <remarks/>
        public short MaxAmountType {
            get {
                return this.maxAmountTypeField;
            }
            set {
                this.maxAmountTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> MaxAmountValue {
            get {
                return this.maxAmountValueField;
            }
            set {
                this.maxAmountValueField = value;
            }
        }
        
        /// <remarks/>
        public short IsRequired {
            get {
                return this.isRequiredField;
            }
            set {
                this.isRequiredField = value;
            }
        }
        
        /// <remarks/>
        public short IsPackage {
            get {
                return this.isPackageField;
            }
            set {
                this.isPackageField = value;
            }
        }
        
        /// <remarks/>
        public short DifferentSupplier {
            get {
                return this.differentSupplierField;
            }
            set {
                this.differentSupplierField = value;
            }
        }
        
        /// <remarks/>
        public short AllowRemark {
            get {
                return this.allowRemarkField;
            }
            set {
                this.allowRemarkField = value;
            }
        }
        
        /// <remarks/>
        public string RemarkNoticeCN {
            get {
                return this.remarkNoticeCNField;
            }
            set {
                this.remarkNoticeCNField = value;
            }
        }
        
        /// <remarks/>
        public string RemarkNoticeEN {
            get {
                return this.remarkNoticeENField;
            }
            set {
                this.remarkNoticeENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TimeLimit {
            get {
                return this.timeLimitField;
            }
            set {
                this.timeLimitField = value;
            }
        }
        
        /// <remarks/>
        public string ChannelID {
            get {
                return this.channelIDField;
            }
            set {
                this.channelIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> HiddenSalePrice {
            get {
                return this.hiddenSalePriceField;
            }
            set {
                this.hiddenSalePriceField = value;
            }
        }
        
        /// <remarks/>
        public string IsVisible {
            get {
                return this.isVisibleField;
            }
            set {
                this.isVisibleField = value;
            }
        }
        
        /// <remarks/>
        public short OptionalHotelType {
            get {
                return this.optionalHotelTypeField;
            }
            set {
                this.optionalHotelTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> ExchangeType {
            get {
                return this.exchangeTypeField;
            }
            set {
                this.exchangeTypeField = value;
            }
        }
        
        /// <remarks/>
        public string TripCaution {
            get {
                return this.tripCautionField;
            }
            set {
                this.tripCautionField = value;
            }
        }
        
        /// <remarks/>
        public string ImportantClause {
            get {
                return this.importantClauseField;
            }
            set {
                this.importantClauseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> OptionalExtType {
            get {
                return this.optionalExtTypeField;
            }
            set {
                this.optionalExtTypeField = value;
            }
        }
        
        /// <remarks/>
        public GetOptionalHotelRelationType GetOptionalHotelRelationType {
            get {
                return this.getOptionalHotelRelationTypeField;
            }
            set {
                this.getOptionalHotelRelationTypeField = value;
            }
        }
        
        /// <remarks/>
        public GetOptionalHotelVacationTicketType GetOptionalHotelVacationTicketType {
            get {
                return this.getOptionalHotelVacationTicketTypeField;
            }
            set {
                this.getOptionalHotelVacationTicketTypeField = value;
            }
        }
        
        /// <remarks/>
        public string IsDelete {
            get {
                return this.isDeleteField;
            }
            set {
                this.isDeleteField = value;
            }
        }
        
        /// <remarks/>
        public string InternalMemo {
            get {
                return this.internalMemoField;
            }
            set {
                this.internalMemoField = value;
            }
        }
        
        /// <remarks/>
        public string OperationNotes {
            get {
                return this.operationNotesField;
            }
            set {
                this.operationNotesField = value;
            }
        }
        
        /// <remarks/>
        public string BookLimit {
            get {
                return this.bookLimitField;
            }
            set {
                this.bookLimitField = value;
            }
        }
        
        /// <remarks/>
        public string GroupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
            }
        }
        
        /// <remarks/>
        public string PackageDesc {
            get {
                return this.packageDescField;
            }
            set {
                this.packageDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ctrip.com/")]
    public partial class GetOptionalHotelResponse {
        
        private OptionalHotel[] optionalHotelListField;
        
        private string responseStatusField;
        
        /// <remarks/>
        public OptionalHotel[] OptionalHotelList {
            get {
                return this.optionalHotelListField;
            }
            set {
                this.optionalHotelListField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ctrip.com/")]
    public partial class HotelGroupInterfaceRoomTypeEntity {
        
        private int interfaceRoomTypeIDField;
        
        private int roomField;
        
        private string roomNameField;
        
        private int minStateField;
        
        private int promoteTypeField;
        
        private int breakfastField;
        
        private int personField;
        
        private int hotelField;
        
        private string hotelGroupRoomTypeCodeField;
        
        private string hotelGroupRoomNameField;
        
        private string hotelGroupHotelCodeField;
        
        private string hotelGroupBrandField;
        
        private string hotelGroupRatePlanCodeField;
        
        private string hotelGroupBookingCodeField;
        
        private string hotelGroupChainCodeField;
        
        private string hotelNameField;
        
        /// <remarks/>
        public int InterfaceRoomTypeID {
            get {
                return this.interfaceRoomTypeIDField;
            }
            set {
                this.interfaceRoomTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public int Room {
            get {
                return this.roomField;
            }
            set {
                this.roomField = value;
            }
        }
        
        /// <remarks/>
        public string RoomName {
            get {
                return this.roomNameField;
            }
            set {
                this.roomNameField = value;
            }
        }
        
        /// <remarks/>
        public int MinState {
            get {
                return this.minStateField;
            }
            set {
                this.minStateField = value;
            }
        }
        
        /// <remarks/>
        public int PromoteType {
            get {
                return this.promoteTypeField;
            }
            set {
                this.promoteTypeField = value;
            }
        }
        
        /// <remarks/>
        public int Breakfast {
            get {
                return this.breakfastField;
            }
            set {
                this.breakfastField = value;
            }
        }
        
        /// <remarks/>
        public int Person {
            get {
                return this.personField;
            }
            set {
                this.personField = value;
            }
        }
        
        /// <remarks/>
        public int Hotel {
            get {
                return this.hotelField;
            }
            set {
                this.hotelField = value;
            }
        }
        
        /// <remarks/>
        public string HotelGroupRoomTypeCode {
            get {
                return this.hotelGroupRoomTypeCodeField;
            }
            set {
                this.hotelGroupRoomTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        public string HotelGroupRoomName {
            get {
                return this.hotelGroupRoomNameField;
            }
            set {
                this.hotelGroupRoomNameField = value;
            }
        }
        
        /// <remarks/>
        public string HotelGroupHotelCode {
            get {
                return this.hotelGroupHotelCodeField;
            }
            set {
                this.hotelGroupHotelCodeField = value;
            }
        }
        
        /// <remarks/>
        public string HotelGroupBrand {
            get {
                return this.hotelGroupBrandField;
            }
            set {
                this.hotelGroupBrandField = value;
            }
        }
        
        /// <remarks/>
        public string HotelGroupRatePlanCode {
            get {
                return this.hotelGroupRatePlanCodeField;
            }
            set {
                this.hotelGroupRatePlanCodeField = value;
            }
        }
        
        /// <remarks/>
        public string HotelGroupBookingCode {
            get {
                return this.hotelGroupBookingCodeField;
            }
            set {
                this.hotelGroupBookingCodeField = value;
            }
        }
        
        /// <remarks/>
        public string HotelGroupChainCode {
            get {
                return this.hotelGroupChainCodeField;
            }
            set {
                this.hotelGroupChainCodeField = value;
            }
        }
        
        /// <remarks/>
        public string HotelName {
            get {
                return this.hotelNameField;
            }
            set {
                this.hotelNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ctrip.com/")]
    public partial class GetHotelGroupInterfaceRoomTypeListResponse {
        
        private HotelGroupInterfaceRoomTypeEntity[] hotelGroupInterfaceRoomTypeListField;
        
        /// <remarks/>
        public HotelGroupInterfaceRoomTypeEntity[] HotelGroupInterfaceRoomTypeList {
            get {
                return this.hotelGroupInterfaceRoomTypeListField;
            }
            set {
                this.hotelGroupInterfaceRoomTypeListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ctrip.com/")]
    public partial class SetOptionalHotelRelationResponse {
        
        private string responseStatusField;
        
        /// <remarks/>
        public string ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ctrip.com/")]
    public partial class OptionalHotelRelation {
        
        private int optionalHotelIDField;
        
        private string captionDispCNField;
        
        private string captionDispENField;
        
        private string unitDispCNField;
        
        private string unitDispENField;
        
        private string descriptionCNField;
        
        private string descriptionENField;
        
        private string currencyCodeField;
        
        private short maxAmountTypeField;
        
        private System.Nullable<int> maxAmountValueField;
        
        private short isRequiredField;
        
        private short isPackageField;
        
        private short differentSupplierField;
        
        private short allowRemarkField;
        
        private string remarkNoticeCNField;
        
        private string remarkNoticeENField;
        
        private System.Nullable<int> timeLimitField;
        
        private string channelIDField;
        
        private System.Nullable<bool> hiddenSalePriceField;
        
        private string isVisibleField;
        
        private short optionalHotelTypeField;
        
        private System.Nullable<short> exchangeTypeField;
        
        private string tripCautionField;
        
        private string importantClauseField;
        
        private System.Nullable<short> optionalExtTypeField;
        
        private int optionalStandardIDField;
        
        private string internalMemoField;
        
        private string operationNotesField;
        
        private string bookLimitField;
        
        private string groupNameField;
        
        private string packageDescField;
        
        private string operatorUidField;
        
        /// <remarks/>
        public int OptionalHotelID {
            get {
                return this.optionalHotelIDField;
            }
            set {
                this.optionalHotelIDField = value;
            }
        }
        
        /// <remarks/>
        public string CaptionDispCN {
            get {
                return this.captionDispCNField;
            }
            set {
                this.captionDispCNField = value;
            }
        }
        
        /// <remarks/>
        public string CaptionDispEN {
            get {
                return this.captionDispENField;
            }
            set {
                this.captionDispENField = value;
            }
        }
        
        /// <remarks/>
        public string UnitDispCN {
            get {
                return this.unitDispCNField;
            }
            set {
                this.unitDispCNField = value;
            }
        }
        
        /// <remarks/>
        public string UnitDispEN {
            get {
                return this.unitDispENField;
            }
            set {
                this.unitDispENField = value;
            }
        }
        
        /// <remarks/>
        public string DescriptionCN {
            get {
                return this.descriptionCNField;
            }
            set {
                this.descriptionCNField = value;
            }
        }
        
        /// <remarks/>
        public string DescriptionEN {
            get {
                return this.descriptionENField;
            }
            set {
                this.descriptionENField = value;
            }
        }
        
        /// <remarks/>
        public string CurrencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
            }
        }
        
        /// <remarks/>
        public short MaxAmountType {
            get {
                return this.maxAmountTypeField;
            }
            set {
                this.maxAmountTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> MaxAmountValue {
            get {
                return this.maxAmountValueField;
            }
            set {
                this.maxAmountValueField = value;
            }
        }
        
        /// <remarks/>
        public short IsRequired {
            get {
                return this.isRequiredField;
            }
            set {
                this.isRequiredField = value;
            }
        }
        
        /// <remarks/>
        public short IsPackage {
            get {
                return this.isPackageField;
            }
            set {
                this.isPackageField = value;
            }
        }
        
        /// <remarks/>
        public short DifferentSupplier {
            get {
                return this.differentSupplierField;
            }
            set {
                this.differentSupplierField = value;
            }
        }
        
        /// <remarks/>
        public short AllowRemark {
            get {
                return this.allowRemarkField;
            }
            set {
                this.allowRemarkField = value;
            }
        }
        
        /// <remarks/>
        public string RemarkNoticeCN {
            get {
                return this.remarkNoticeCNField;
            }
            set {
                this.remarkNoticeCNField = value;
            }
        }
        
        /// <remarks/>
        public string RemarkNoticeEN {
            get {
                return this.remarkNoticeENField;
            }
            set {
                this.remarkNoticeENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TimeLimit {
            get {
                return this.timeLimitField;
            }
            set {
                this.timeLimitField = value;
            }
        }
        
        /// <remarks/>
        public string ChannelID {
            get {
                return this.channelIDField;
            }
            set {
                this.channelIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> HiddenSalePrice {
            get {
                return this.hiddenSalePriceField;
            }
            set {
                this.hiddenSalePriceField = value;
            }
        }
        
        /// <remarks/>
        public string IsVisible {
            get {
                return this.isVisibleField;
            }
            set {
                this.isVisibleField = value;
            }
        }
        
        /// <remarks/>
        public short OptionalHotelType {
            get {
                return this.optionalHotelTypeField;
            }
            set {
                this.optionalHotelTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> ExchangeType {
            get {
                return this.exchangeTypeField;
            }
            set {
                this.exchangeTypeField = value;
            }
        }
        
        /// <remarks/>
        public string TripCaution {
            get {
                return this.tripCautionField;
            }
            set {
                this.tripCautionField = value;
            }
        }
        
        /// <remarks/>
        public string ImportantClause {
            get {
                return this.importantClauseField;
            }
            set {
                this.importantClauseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> OptionalExtType {
            get {
                return this.optionalExtTypeField;
            }
            set {
                this.optionalExtTypeField = value;
            }
        }
        
        /// <remarks/>
        public int OptionalStandardID {
            get {
                return this.optionalStandardIDField;
            }
            set {
                this.optionalStandardIDField = value;
            }
        }
        
        /// <remarks/>
        public string InternalMemo {
            get {
                return this.internalMemoField;
            }
            set {
                this.internalMemoField = value;
            }
        }
        
        /// <remarks/>
        public string OperationNotes {
            get {
                return this.operationNotesField;
            }
            set {
                this.operationNotesField = value;
            }
        }
        
        /// <remarks/>
        public string BookLimit {
            get {
                return this.bookLimitField;
            }
            set {
                this.bookLimitField = value;
            }
        }
        
        /// <remarks/>
        public string GroupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
            }
        }
        
        /// <remarks/>
        public string PackageDesc {
            get {
                return this.packageDescField;
            }
            set {
                this.packageDescField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorUid {
            get {
                return this.operatorUidField;
            }
            set {
                this.operatorUidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ctrip.com/")]
    public partial class GetOptionalHotelRelationResponse {
        
        private int productTypeField;
        
        private int[] productIDListField;
        
        private OptionalHotelRelation optionalHotelField;
        
        /// <remarks/>
        public int ProductType {
            get {
                return this.productTypeField;
            }
            set {
                this.productTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ProductID", IsNullable=false)]
        public int[] ProductIDList {
            get {
                return this.productIDListField;
            }
            set {
                this.productIDListField = value;
            }
        }
        
        /// <remarks/>
        public OptionalHotelRelation OptionalHotel {
            get {
                return this.optionalHotelField;
            }
            set {
                this.optionalHotelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ctrip.com/")]
    public partial class HotelList {
        
        private int hotelField;
        
        private string hotelNameField;
        
        /// <remarks/>
        public int Hotel {
            get {
                return this.hotelField;
            }
            set {
                this.hotelField = value;
            }
        }
        
        /// <remarks/>
        public string HotelName {
            get {
                return this.hotelNameField;
            }
            set {
                this.hotelNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ctrip.com/")]
    public partial class GetHotelInfoResponse {
        
        private int totalPageField;
        
        private int currentPageField;
        
        private int totalNumField;
        
        private HotelList[] hotelListField;
        
        /// <remarks/>
        public int TotalPage {
            get {
                return this.totalPageField;
            }
            set {
                this.totalPageField = value;
            }
        }
        
        /// <remarks/>
        public int CurrentPage {
            get {
                return this.currentPageField;
            }
            set {
                this.currentPageField = value;
            }
        }
        
        /// <remarks/>
        public int TotalNum {
            get {
                return this.totalNumField;
            }
            set {
                this.totalNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("HotelList")]
        public HotelList[] HotelList {
            get {
                return this.hotelListField;
            }
            set {
                this.hotelListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ctrip.com/")]
    public partial class SetMappingInfoResponse {
        
        private string resultField;
        
        /// <remarks/>
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ctrip.com/")]
    public partial class OrderApplyPaymentResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ctrip.com/")]
    public partial class ResponseHead {
        
        private string cultureField;
        
        private string versionField;
        
        private string userIDField;
        
        private string timestampField;
        
        private string requestIDField;
        
        private string sessionIDField;
        
        private string referenceIDField;
        
        private string transNoField;
        
        private ResultCode resultCodeField;
        
        private string resultNoField;
        
        private string resultMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Culture {
            get {
                return this.cultureField;
            }
            set {
                this.cultureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RequestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReferenceID {
            get {
                return this.referenceIDField;
            }
            set {
                this.referenceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TransNo {
            get {
                return this.transNoField;
            }
            set {
                this.transNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ResultCode ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ResultNo {
            get {
                return this.resultNoField;
            }
            set {
                this.resultNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ResultMsg {
            get {
                return this.resultMsgField;
            }
            set {
                this.resultMsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ctrip.com/")]
    public enum ResultCode {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Fail,
        
        /// <remarks/>
        UnKown,
        
        /// <remarks/>
        Retry,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Response))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ctrip.com/")]
    public partial class ResponseBase {
        
        private ResponseHead headerInfoField;
        
        /// <remarks/>
        public ResponseHead HeaderInfo {
            get {
                return this.headerInfoField;
            }
            set {
                this.headerInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ctrip.com/")]
    public partial class Response : ResponseBase {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GetHotelInfoResponse", typeof(GetHotelInfoResponse), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("GetMappingInfoResponseList", typeof(GetMappingInfoListReponse), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("GetMasterHotelInfoResponse", typeof(GetMasterHotelInfoResponse), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("GetOptionalCategoryResponse", typeof(GetOptionalCategoryResponse), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("GetOptionalHotelRelationResponse", typeof(GetOptionalHotelRelationResponse), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("GetOptionalHotelResponse", typeof(GetOptionalHotelResponse), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("GetOptionalStandardResponse", typeof(GetOptionalStandardResponse), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("HotelGroupInterfaceRoomTypeListResponse", typeof(GetHotelGroupInterfaceRoomTypeListResponse), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("OrderApplyPaymentResponse", typeof(OrderApplyPaymentResponse), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("OrderCheckInNoticeResponse", typeof(OrderCheckInNoticeResponse), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("SetMappingInfoReponse", typeof(SetMappingInfoResponse), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("SetOptionalHotelRelationResponse", typeof(SetOptionalHotelRelationResponse), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("SetOptionalHotelResponse", typeof(SetOptionalHotelResponse), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ctrip.com/")]
    public partial class DomesticPushOrderStatusResponse {
        
        private string returnCodeField;
        
        private string returnDescriptField;
        
        /// <remarks/>
        public string ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ReturnDescript {
            get {
                return this.returnDescriptField;
            }
            set {
                this.returnDescriptField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ctrip.com/")]
    public partial class CtripSoapResponse {
        
        private string messageField;
        
        private int resultCodeField;
        
        private object itemField;
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public int ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DomesticPushOrderStatusResponse", typeof(DomesticPushOrderStatusResponse), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Response", typeof(Response), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    public delegate void GetTokenCompletedEventHandler(object sender, GetTokenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CtripSoapResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CtripSoapResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    public delegate void RequestCompletedEventHandler(object sender, RequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CtripSoapResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CtripSoapResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    public delegate void AdapterRequestCompletedEventHandler(object sender, AdapterRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AdapterRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AdapterRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
